### ISSUE TITLE
托盘图标颜色太浅

### ISSUE THREAD

**Issue by fuzy112** [XUJINKAI/OneQuick#10]
![default](https://user-images.githubusercontent.com/10750252/33272577-8920bcb2-d3c5-11e7-8251-5c572692dba2.png)

如图，第三个图标是 OneQuick，几乎看不到🤦。

Win 8 x64 非商店版

**Comment by XUJINKAI** [comment]
![image](https://user-images.githubusercontent.com/6772799/39119274-06d47b1e-471e-11e8-94d6-9e7673b0bb99.png)
![image](https://user-images.githubusercontent.com/6772799/39119345-2a5130f0-471e-11e8-91a8-a0be19a985f4.png)
win10中还行XD
个人能力有限，又没有美工基础，图标暂时不会改了
