### ISSUE TITLE
屏幕边缘界面bug

### ISSUE THREAD

**Issue by Lanmer** [XUJINKAI/OneQuick#100]
在设置自定义快捷键时，想要实现的逻辑为，A软件内有某快捷键为 ctrl+alt+right,在onequick中设置热键crtl+alt+right，想要onequcik实现在键盘模拟 ctrl+alt+right，目前的逻辑似乎是onequick声明了全局快捷键，并未模拟 ctrl+alt+right 实现A软件的功能

**Comment by XUJINKAI** [comment]
请问意思是，A软件里边 ctrl+alt+right 会执行某个功能；
想利用OneQuick 模拟ctrl+alt+right，控制A软件。是这个意思么？

首先得确定A软件监听的是全局热键，就是说A软件窗口不在最前端（不激活）时，按 ctrl+alt+right 是有用的。
然后程序里可以这么设置：
![image](https://github.com/user-attachments/assets/4d1e037d-594f-4dfa-b49c-40a5f6739cb1)

**Comment by Lanmer** [comment]
我怀疑是我另一个软件的问题，我尝试在potplayer中添加快捷键 ctrl+ALT+NUM1，执行播放下一文件的命令；键盘按下ctrl+ALT+NUM1，能够正常执行快捷键功能，但在onequick中执行此快捷键，似乎无法使potplayer播放下一个文件，图片3中已设置全局快捷键
![图片](https://github.com/user-attachments/assets/52f24d86-678a-4773-8d6c-e0bffc647871)
![图片](https://github.com/user-attachments/assets/817ddf69-9530-4064-bb69-4da2e53f03bb)
![图片](https://github.com/user-attachments/assets/364dd996-a50f-4667-8716-33e8cff4cb2e)

**Comment by XUJINKAI** [comment]
新版10.2已经修复了这个问题
