### ISSUE TITLE
关于复制搜索-直接运行URL

### ISSUE THREAD

**Issue by Feykrosias** [XUJINKAI/OneQuick#101]
理论上来说，复制搜索是等价于【”直接运行命令“并”把%s替换为剪切板内容“】对吧？
那么按照如下方式添加一条“直接运行”的自定义项，目的是直接打开剪切板中的网址
![image](https://github.com/user-attachments/assets/b61210a6-b917-486a-879a-0f040815bc43)
却会报错，无法打开
![image](https://github.com/user-attachments/assets/ab2ffd48-62a6-4ebf-b89e-ca2747ffeb77)
请问是什么原因呢

**Comment by XUJINKAI** [comment]
不是的，%s替换为剪贴板内容后，还会进行URL编码，
所以`https://`被替换为了`https%3a%2f%2f`，就无法运行了。
【直接打开剪贴板中的网址】这个功能目前不支持，后续会让运行命令更智能一些，感谢反馈。

**Comment by Feykrosias** [comment]
好的，补充一下剪切板内容不包括`https://`的情况：
![image](https://github.com/user-attachments/assets/3c12b877-67d4-4c5f-80d4-4dc1aa39599e)

**Comment by XUJINKAI** [comment]
这个功能搞定了，10.3.0，还在认证中，最多3天以后就能在商店看到了。
