### ISSUE TITLE
两个个显示器如何让边缘触发(切换虚拟桌面)，只切换当前鼠标所在的显示器？

### ISSUE THREAD

**Issue by CCbird** [XUJINKAI/OneQuick#102]
不想两个显示器都一起切换虚拟桌面，请问有内置此功能吗

**Comment by XUJINKAI** [comment]
这个是系统就这么设计的，切换虚拟桌面和几个显示器没关系，所有显示器都是同一个虚拟桌面。

**Comment by CCbird** [comment]
> 这个是系统就这么设计的，切换虚拟桌面和几个显示器没关系，所有显示器都是同一个虚拟桌面。

好的 感谢回复
