### ISSUE TITLE
根据当前的程序自动启停

### ISSUE THREAD

**Issue by SunnyRx** [XUJINKAI/OneQuick#103]
记得旧版本可以按 F10 停用或启用 OneQuick，现在没有了，希望能有这个功能。
有些场景会希望暂时停用 OneQuick，例如玩游戏的时候可能鼠标会无意中停在屏幕边缘用滚轮，导致触发了 OneQuick 的功能。

**Comment by XUJINKAI** [comment]
之后版本会有更聪明的办法解决这个问题，感谢支持。现在只能通过右键托盘图标切换。

**Comment by XUJINKAI** [comment]
10.4已更新，到设置中添加应用名即可
