### ISSUE TITLE
鼠标滚轮灵敏度限制

### ISSUE THREAD

**Issue by 6vision** [XUJINKAI/OneQuick#105]
当设置屏幕边缘切换虚拟桌面时候，鼠标滚轮滑动一下，桌面能来回切换好几次，好像和鼠标灵敏度没关系~

**Comment by XUJINKAI** [comment]
可能是因为无极的滚轮。之后会想办法限制一下，提升这方面的体验

**Comment by 6vision** [comment]
> 可能是因为无极的滚轮。之后会想办法限制一下，提升这方面的体验

我试过罗技的，很经常出现。我现在用的联想小新M1，情况好一些
![image](https://github.com/user-attachments/assets/57d412df-439f-45f9-9ddb-44797633d1a5)

**Comment by XUJINKAI** [comment]
10.4已更新，可以到设置里调大值试试

**Comment by 6vision** [comment]
> 10.4已更新，可以到设置里调大值试试

感谢，终于屏幕不乱跳了
