### ISSUE TITLE
Home End热键执行异常

### ISSUE THREAD

**Issue by LoongGingko** [XUJINKAI/OneQuick#110]
写代码时经常用到，比较头痛的一个问题，请看图
![Snipaste_2024_12_10_14-43-58](https://github.com/user-attachments/assets/d6681cf5-68c9-468d-8796-82bb56758359)

**Comment by XUJINKAI** [comment]
感谢反馈，试了一下确实，之后版本修复。

**Comment by XUJINKAI** [comment]
请更新到10.4.2版本，已修复此问题。

感谢您的反馈，可以的话请您在商店给个好评❤️
