### ISSUE TITLE
希望能增加调整屏幕亮度的选项

### ISSUE THREAD

**Issue by Emrys365** [XUJINKAI/OneQuick#16]
如题

**Comment by Bai-Jinlin** [comment]
非常期待这个功能

**Comment by XUJINKAI** [comment]
目前不会考虑，理由：
1. 对外接屏幕无效，时灵时不灵会对更多用户造成困扰
2. 笔记本屏幕亮度都有自带热键，而且win10中通知中心就可以调节

即使是win10通知中心的调节，对外接屏幕也无效，所以目前不会做。

**Comment by CNHSY** [comment]
挺怀念AHK时代的这个功能的

**Comment by observerkei** [comment]
要是有就好了，（妄想使用触控板吃遍操作的用户）

**Comment by XUJINKAI** [comment]
#47
