### ISSUE TITLE
程序有时会失效或错误（修饰键记录错误）

### ISSUE THREAD

**Issue by XUJINKAI** [XUJINKAI/OneQuick#2]
临时解决办法：失效后手动把ctrl alt shift win按一遍，或重新启动程序。

**Comment by XUJINKAI** [comment]
ctrl alt delete会按下ctrl 和alt ，但程序不会记录到弹起，导致以后的快捷键都多了ctrl和alt。

**Comment by wyao666** [comment]
短语替换用不起来！不知道怎么使用，和输入法有关吗？
