### ISSUE TITLE
希望能支持cmder中词语替换

### ISSUE THREAD

**Issue by lizhihao6** [XUJINKAI/OneQuick#23]
因为保存了很多ip的词语替换
所以希望能在cmder中支持词语替换，方便ssh

**Comment by XUJINKAI** [comment]
你是不是以管理员身份运行cmder了 因为系统限制 管理员和非管理员的程序没法沟通的

**Comment by lizhihao6** [comment]
嗯嗯是的,原来如此……thx^_^

发自我的 iPad

在 2018年4月6日，上午12:32，XJK <notifications@github.com<mailto:notifications@github.com>> 写道：


你是不是以管理员身份运行cmder了 因为系统限制 管理员和非管理员的程序直接没法沟通的
