### ISSUE TITLE
开机启动时读取配置文件出错

### ISSUE THREAD

**Issue by Go2War** [XUJINKAI/OneQuick#24]
日志如下，不知是什么原因？
[0x2614de20000][2018-03-02 08:04:36] [ERROR], 未将对象引用设置到对象的实例。
   在 OneQuick.Core.EntryServer.Add(IEnumerable`1 triggers)
   在 OneQuick.Config.ConfigEntry.ForceInstallTriggers()
   在 OneQuick.Config.Configuration.set_IsInstalled(Boolean value)
   在 OneQuick.MainWindow.set_Configur(Configuration value)
   在 OneQuick.MainWindow.LogException(Action action, Boolean throwExp, Action`1 catchCallback, Action finallyCallback)

**Comment by Go2War** [comment]
升级之后没有这个问题了，但有时会在工作中弹出主界面，有时是在刚启动系统时。

**Comment by XUJINKAI** [comment]
看一下“显示/隐藏界面”的热键设置？

**Comment by Go2War** [comment]
已解决。之前“显示/隐藏界面”的热键无，看到你的提示后设了个不用的热键，不再不时弹出主界面。

**Comment by XUJINKAI** [comment]
可不可以帮忙测试下，再把那个热键删了，看会不会又出现这个问题，如果有的话还真是bug

**Comment by Go2War** [comment]
测试一段时间后，没有出现之前提及的情况。还有之前出现过两次自行停止（类推的话猜可能是“运行/停止”热键），现在也没有了。

**Comment by XUJINKAI** [comment]
感谢测试，应该是升级1.0导致的，那两个功能的配置我挪了位置
