### ISSUE TITLE
托盘态长期不使用, 程序自动退出.

### ISSUE THREAD

**Issue by slivermeteor** [XUJINKAI/OneQuick#26]
![image](https://user-images.githubusercontent.com/20829599/37752942-7c25873a-2dd5-11e8-9b66-9dad6291d487.png)
版本如上.
长期不使用, 程序似乎会自动退出.

**Comment by XUJINKAI** [comment]
http://onequick.org/feedback  
参考这个页面，需要崩溃时的详细信息  
另外请先升级1.0

**Comment by slivermeteor** [comment]
问题复现方法:
后台长期挂着，自动崩溃退出。
安装环境:
![image](https://user-images.githubusercontent.com/20829599/39345051-e785d70a-4a18-11e8-8bf0-edda6c777ba5.png)
商店版
![image](https://user-images.githubusercontent.com/20829599/39344964-60581590-4a18-11e8-88d8-9ad4e791006e.png)
日志如下:  
![image](https://user-images.githubusercontent.com/20829599/39344987-7d2a0598-4a18-11e8-832a-bd38888cb42f.png)
系统日志如下:
![image](https://user-images.githubusercontent.com/20829599/39345021-b748d218-4a18-11e8-8d50-f4046344abf4.png)

**Comment by XUJINKAI** [comment]
已修复
