### ISSUE TITLE
the option for Copy-Search

### ISSUE THREAD

**Issue by BenjaminDbb** [XUJINKAI/OneQuick#27]
Hi, It's one of  the most wonderful software I used. 
Recently, I update OneQuick to version 1.0.0.39257 OneQuick Lite (Desktop) x64.

I see that Copy-Search hotkey has been changed to Ctrl+C twice and no option for customizing Copy-Search hotkey. There now exists some conflict with other (Dictionary) software possibly. 

Could you please add the option to customize it? Thank you.

**Comment by XUJINKAI** [comment]
you can customize hotkey
![image](https://user-images.githubusercontent.com/6772799/39118246-8ad1abb0-471b-11e8-95fc-50976de9acb5.png)

(UI should be enhance more i admit)

**Comment by BenjaminDbb** [comment]
When I used the OneQuick of AHK version, I remember, Select the Text, push```Ctrl + Shift + C``` first, and then push ```g```.

Now, I should select the Text, push ```Ctrl + C ``` twice first, and then push ```g```.

Unfortunately,  there now exists some conflict with other software possibly. for example, some Dictionary software set hotkey ```Ctrl + C + C``` to translate a word from clipboard.

When you want to use OneQuick to search something in google, select it, push ```Ctrl + C ``` twice, and will active the translation software, the result box will always pop up.  It looks awful.

Could you please add the option to customize **```Ctrl + C ```  twice**? Thank you.

**Comment by XUJINKAI** [comment]
I can give an option to handle the second ctrl_c , then other app will not detect the ctrl_c twice event.

When press ctrl_shift_c in ahk version, onequick send ctrl_c to system and then wait 100ms for clipbard change, this caused much problem.  
Considering stability, it's better to listen ctrl_c. System will do the copy action.  

I can't find a hotkey combination which is not conflict to any software, and i don't want to make this app more complicate for now.

**Comment by swun90** [comment]
能不能定制这个 `Ctrl + C` 啊，如果 `shift + ctrl + c` 有问题，比如`win + ctrl + c` 可不可以？
两次 `ctrl + c` 实在没法用，我的电脑上根本不起作用。

**Comment by XUJINKAI** [comment]
@swun90 暂时没这个打算，请看看上边的解释，ctrl_c是系统本身的复制键，比较稳定。
你可以再开个issue，看看没法用的问题在哪。

另外1.1版本已经把第二个ctrl_c屏蔽了，应该不会再同时触发其他软件。
