### ISSUE TITLE
如何配置能更改为qq音乐或网易云音乐切换

### ISSUE THREAD

**Issue by Yogurt-lei** [XUJINKAI/OneQuick#3]
如何配置能更改为qq音乐或网易云音乐上一首下一首~

**Comment by XUJINKAI** [comment]
OneQuick目前的做法是模拟键盘上的按键，效果和你按键盘上的上一首下一首按键（如果有）一样，但有的软件没有监听键盘相关的按键，OneQuick就会失去作用。

而OneQuick目前还有很多其他功能没有完成，为特定软件优化的优先级非常靠后。

如果使用win10的话，可以安装对应的商店版本。

**Comment by Yogurt-lei** [comment]
麻烦再问一下 就是这个上一首下一首的按键  默认设置的是什么讷。

**Comment by XUJINKAI** [comment]
呃 没懂你的意思 
有的键盘上会有上一首/下一首/暂停的按键 OneQuick模拟的就是这个

**Comment by szzhiyang** [comment]
@Yogurt-lei 用 UWP 版本的 QQ 音乐和网易云音乐就好了。
