### ISSUE TITLE
窗口置顶失效

### ISSUE THREAD

**Issue by mfkof** [XUJINKAI/OneQuick#30]
OneQuick Lite (Desktop) v1.0.0   Win10 64bit
使用爱奇艺UWP版看视频，窗口模式里设置好了置顶，在双击鼠标进入全屏后再退出，置顶就失效了。

**Comment by XUJINKAI** [comment]
因为退出全屏的时候爱奇艺会重新设置窗口属性，这个没法修，只能重新再设置置顶
