### ISSUE TITLE
Pro版，后台长时间后崩溃退出。

### ISSUE THREAD

**Issue by slivermeteor** [XUJINKAI/OneQuick#31]
复现方法：
后台运行，一段事件后，自动崩溃退出。
日志：
![image](https://user-images.githubusercontent.com/20829599/39958060-0e9af47e-5630-11e8-9894-61a2f53c3d15.png)
安装环境：
![image](https://user-images.githubusercontent.com/20829599/39958061-1cb883dc-5630-11e8-94b5-c30bdebdc88c.png)
安装版本：
![image](https://user-images.githubusercontent.com/20829599/39958067-2a9b368e-5630-11e8-864e-299ff78c3f22.png)
事件查看器错误信息：
![image](https://user-images.githubusercontent.com/20829599/39958070-428e2fee-5630-11e8-8a92-c9583ce1c7bc.png)

**Comment by XUJINKAI** [comment]
我还以为修复了，下一个版本直接套一个try catch解决 ╮(╯▽╰)╭

**Comment by XUJINKAI** [comment]
1.2.2版本，这个问题应该不会再有了
