### ISSUE TITLE
与360冲突的解决办法

### ISSUE THREAD

**Issue by LANTERNLALA** [XUJINKAI/OneQuick#32]
在360运行的情况下使用onequick，电脑马上卡顿，然后onequick 就会崩溃掉，现在有解决这个问题的办法吗？之后有希望解决吗？

**Comment by LANTERNLALA** [comment]
我好像找到解决办法了。
在360的木马查杀界面将onequick文件夹加入信任区，之后就不会冲突了。

**Comment by XUJINKAI** [comment]
囧
