### ISSUE TITLE
1.2.4版本无法订阅怎么办？

### ISSUE THREAD

**Issue by wxy2k** [XUJINKAI/OneQuick#33]
win10 系统，1.2.4版，点订阅后会出现一个应用商店窗口，但没显示内容就自动关闭了，三个订阅选项都是这样的情况，请问这该怎么解决？

**Comment by XUJINKAI** [comment]
能出来商店页面的话可能是你系统的问题，更新一下？

**Comment by wxy2k** [comment]
我的系统已经是最新的了，1803（内部版本17134.48）

**Comment by XUJINKAI** [comment]
自动关闭是关闭购买窗口还是onequick 日志贴上来看看

**Comment by H4M5TER** [comment]
同一个情况 购买窗口不显示 过会自己关闭
