### ISSUE TITLE
复制搜索不太好用

### ISSUE THREAD

**Issue by CNHSY** [XUJINKAI/OneQuick#34]
复制搜索功能没有AHK时代的onequick好用，而且没有教程不太清楚怎么使用这一套快捷键，（快速按两下CTRL+C，然后数字分组+字母）不知道对不对
只有偶尔触发了几次搜索，其他时间都没有反应。
我还是比较喜欢以前的CTRL+SHIFT+C然后有一个选项表单出来然后再按对应字母的快捷键

新的onequick功能很强大，谢谢作者开发出这么好的软件

**Comment by XUJINKAI** [comment]
不需要”快速“ 两下Ctrl C 再按一下热键
分组的意思是 按一下数字 所有这个分组的就都打开了
分组热键和热键是两个功能

**Comment by CNHSY** [comment]
@XUJINKAI 请问使用“复制搜索“的功能是不是这样子的：
①选中搜索目标
②按两下（app上面说的）ctrl+c
③按”B“（百度搜索）
请问这样子是否正确？如果正确，但它并没有跳出任何网页

**Comment by XUJINKAI** [comment]
啊 发现一个bug 两个Ctrl C的Ctrl要一直按着，也就是Ctrl-C-C，然后松开Ctrl再按B
这个判定我以后修复

**Comment by CNHSY** [comment]
可以了，谢谢😊

**Comment by SUMMERMMTEA** [comment]
一般人应该不会在连续Ctrl+C两次的情况下来松开Ctrl吧，我觉得Ctrl+C+C，按住Ctrl不放也可以激活，这种情况可以保留吧。
