### ISSUE TITLE
是否支持简单的多步快捷键

### ISSUE THREAD

**Issue by blqw** [XUJINKAI/OneQuick#35]
比如VS中经常有的需要按下2次键盘才能触发的快捷键
比如 Ctrl+M,Ctrl+O
表示先按下一下C+M,再按一下C+O

**Comment by XUJINKAI** [comment]
界面上目前没这个功能，因为我xaml比较烂。。。这也是我下一步的计划

你可以修改OneQuick.config文件做到这个效果
Sequence里边的HotkeySingle，复制几个修改就行。
修改这个文件无需退出，界面上不会显示，但实际是有效果的。
![image](https://user-images.githubusercontent.com/6772799/40598839-b162d19c-627c-11e8-8dc1-f4e31a17aa63.png)

**Comment by blqw** [comment]
biangbiangda \mua

**Comment by XUJINKAI** [comment]
#81 @blqw 新版本来了，直接支持。
