### ISSUE TITLE
如何使软件的默认启动方式就是管理员模式?

### ISSUE THREAD

**Issue by blqw** [XUJINKAI/OneQuick#36]
虽然设置了开机启动,但还是要关闭一次之后用管理员方式打开,很不方便

**Comment by XUJINKAI** [comment]
大哥！！！非常感谢！！！
突然有灵感了。
是这样的，UWP注册的应用是无法以管理员模式启动的，所以这个功能我几乎放弃了。
刚才实验了一下，计划任务是可以的！
以下是记录：
1. 勾选以最高权限运行
2. 触发器选登陆时
3. 运行命令是`cmd` 而参数填 `/c  start onequick.exe -h`
4. 在任务管理器里把默认的那个禁用掉
有个缺点是，Cmd会闪一下，然后OneQuick也会闪一下 - -

**需要注意**：OneQuick还没有针对管理员权限做优化，所以通过OneQuick运行的程序权限也是管理员，这可能会造成更多问题，所以慎用。
我之后会把这一套加进去，然后应该就没这个问题了。

**Comment by blqw** [comment]
希望越做越好哈

**Comment by XUJINKAI** [comment]
😏10.3已更新，支持管理员权限了。
