### ISSUE TITLE
是否可以参考罗技鼠标的手势按钮功能

### ISSUE THREAD

**Issue by blqw** [XUJINKAI/OneQuick#37]
![image](https://user-images.githubusercontent.com/9656154/40599165-6a871a7e-627e-11e8-93a5-874beb4366cc.png)
这个功能我一直觉得很好用,可惜在一直存在bug,经常会失效,必须要重启电脑才能恢复
还有就是只支持特殊鼠标的特殊键, 不支持所有的键
如果作者可以右键或者任意鼠标的4,5键上支持就太棒了!!!

**Comment by XUJINKAI** [comment]
鼠标手势是个难题啊，很不好做（对我而言）

**Comment by blqw** [comment]
并不是简单的手势,如果条件允许的话最好可以找个设备体验一下

**Comment by blqw** [comment]
我感觉他的做法是这样的    比如我设置了中键为手势按钮
则 按下中键的时候 锁定鼠标位置(将鼠标的移动范围限制在1个像素)  放开中键时 施放鼠标位置锁定
然后判断鼠标的坐标偏移( 这里不是很确定, 当鼠标锁定之后时候可以在软件上判断鼠标偏移量,还是要从硬件驱动入手?),如果不行, 可以在第二步 将鼠标的移动限制的一个3x3的范围, 通过相对移动完成, 而且对于用户来说也几乎不可感知
然后根据偏移量执行响应的动作

**Comment by XUJINKAI** [comment]
我现在用的API没这个功能，简单查了下，需要用到游戏的技术，这个暂时肯定没有的。

**Comment by blqw** [comment]
你有时间的话 看下这个
我之前做过类似的功能 应该不难 (/偷笑)
https://www.pinvoke.net/default.aspx/user32/ClipCursor.html

**Comment by XUJINKAI** [comment]
好 非常感谢

**Comment by phliulei** [comment]
@blqw 失灵的时候貌似不用重启电脑，只要关闭Logi*进程，重启软件就行了，如果频繁失灵可以写个bat来实现。

**Comment by XUJINKAI** [comment]
v10新版本已更新，欢迎使用。有关功能需求都整理到一个帖子了，这个就先关了。
