### ISSUE TITLE
建议加上一个重要的功能——导出个人设置

### ISSUE THREAD

**Issue by Meow16** [XUJINKAI/OneQuick#4]
每个电脑装了后都要重设一遍实在太累了。。。

另外谢谢作者带来这么好用的软件

**Comment by XUJINKAI** [comment]
设置在“我的文档”里，拷出来就行了

**Comment by Meow16** [comment]
学到啦！不过软件里希望加点提示
我是直接找的win10 UWP目录地址，没想到是我的文档
