### ISSUE TITLE
建议动作增加启动UWP应用的功能

### ISSUE THREAD

**Issue by blqw** [XUJINKAI/OneQuick#41]
我都不知道怎么用热键或者批处理来启动UWP的应用
但是我见过其他工具可以启动他们
比如这个
![image](https://user-images.githubusercontent.com/9656154/41268218-a579d9d2-6e31-11e8-904d-b25b9176e00f.png)

**Comment by XUJINKAI** [comment]
运行命令里填`ms-settings:`试试（启动设置）
这个叫protocol，协议启动。
我还没找到怎么获取这个列表，所以具体的UWP应用你得自己搜了。
在win+R运行窗口里会有一部分提示，可以用来测试。

**Comment by ghost** [comment]
![default](https://user-images.githubusercontent.com/18734999/46899785-68193c00-ceca-11e8-9a9f-1a7715473d6b.png)
直接使用 `ms-todo:` 协议启动

**Comment by XUJINKAI** [comment]
@lhy0403 请问你这个文件是从哪找到的？

**Comment by ghost** [comment]
任务管理器，右键打开文件位置
![default](https://user-images.githubusercontent.com/18734999/46902209-cf97b180-cef3-11e8-90d5-ec10d7a69608.png)
-----
这个文件夹需要获取所有权后访问，具体方法 baidu Bing 或者 Google😏
![default](https://user-images.githubusercontent.com/18734999/46902213-daeadd00-cef3-11e8-8622-e0f036dff8fa.png)
-----
app XML Schemas 文件，包含包信息，双击打开
![default](https://user-images.githubusercontent.com/18734999/46902217-e5a57200-cef3-11e8-9802-5ca47c7097b2.png)
-----
找到以下节点：
![default](https://user-images.githubusercontent.com/18734999/46902276-12a65480-cef5-11e8-85de-9ab8dc576fce.png)
-----
此处为 Microsoft Todo 包文件为例，有两个 Protocol 可以启动 Todo
![default](https://user-images.githubusercontent.com/18734999/46902274-091cec80-cef5-11e8-9fda-f2be9e13ee65.png)

App Menifest 这个文件， 可以参考 [微软官方文档](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-protocol)

**Comment by ghost** [comment]
```C#
PackageManager packageManager = new PackageManager();
IEnumerable<Windows.ApplicationModel.Package> packages = packageManager.FindPackagesForUser("");
Windows.ApplicationModel.Package packagesS = packageManager.FindPackageForUser("", "YOUR_PACKAGE_FULLNAME");
```
- 第一行声明了一个包管理器
- 第二行枚举了安装的所有UWP包
- 第三行根据包名（“YOUR_PACKAGE_FULLNAME”）找到所需的包
--------
（启动啥的应该不难，只是这种方法需要一个
```
xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"
<rescap:Capability Name="packageQuery" />
``` 
权限，可能需要审核过后才能通过应用商店上架）

**Comment by XUJINKAI** [comment]
非常感谢！

**Comment by ddkk3000** [comment]
为什么没有人说增加运行快捷方式的能力？现在还要把要运行的文件拷贝到windows目录，有点麻烦啊，而且有些软件的包真的有点儿大。

**Comment by ddkk3000** [comment]
当然可以通过设置环境变量的方式来实现，可好几个程序的根目录地址都设置到环境变量中，还是有点儿麻烦。

**Comment by ddkk3000** [comment]
好吧，我在补充一句，虽然可以通过添加path为新目录然后新建快捷.ink的方式实现一劳永逸，不过……我还是觉得有点儿麻烦。尤其是在多个设备上同时运行onequick的时候。

**Comment by ddkk3000** [comment]
好的，感谢
________________________________

**Comment by XUJINKAI** [comment]
v10新版本已更新，欢迎使用。有关功能需求都整理到一个帖子了，这个就先关了。

**Comment by XUJINKAI** [comment]
10.4中，更新了一个应用列表，可以查看UWP应用的启动命令
