### ISSUE TITLE
一个超级奇怪的bug

### ISSUE THREAD

**Issue by blqw** [XUJINKAI/OneQuick#42]
![2222](https://user-images.githubusercontent.com/9656154/41395688-3017f582-6fe1-11e8-8dfe-f51dea7f2f4d.gif)

这个工具是 Microsoft To-Do 点住鼠标左键然后往右拖  onequick就弹出来了

**Comment by XUJINKAI** [comment]
https://onequick.org/feedback#-1-2-
重新设置显示界面的快捷键没有效果？

**Comment by blqw** [comment]
不行哦

**Comment by XUJINKAI** [comment]
用的商店版？

有没有时间用下载版测试一下，下载版我可以很快编译，比较容易找到问题所在。

**Comment by XUJINKAI** [comment]
@blqw 请升级1.2.5看看
