### ISSUE TITLE
希望OneQuick能更改下在商店里的名字

### ISSUE THREAD

**Issue by Creeper233** [XUJINKAI/OneQuick#43]
比如改成OneQuick - 热键快捷工具
因为从名字和图标很难让人理解这款软件是干什么的，就不会点开了解

**Comment by Creeper233** [comment]
还有https://github.com/OneQuick/OneQuick.net/wiki里提供的网站http://onequick.org/support 404了，希望能修复下

**Comment by Creeper233** [comment]
还有https://github.com/OneQuick/OneQuick.net/wiki 里提供的网站http://onequick.org/support 404了，希望能修复下

**Comment by XUJINKAI** [comment]
感谢反馈 链接已修复
名字的建议非常好 我研究一下

**Comment by XUJINKAI** [comment]
已改 : )
