### ISSUE TITLE
软件打开空白

### ISSUE THREAD

**Issue by aceseo** [XUJINKAI/OneQuick#45]
独立版本以及商城版本都下载，打开空白无内容，功能也无法执行。
Win10 64位系统。

**Comment by aceseo** [comment]
补充:
未安装任何杀软。
Net版本4.6.2

**Comment by XUJINKAI** [comment]
截个图。
去事件查看器看看有没有问题？
![image](https://user-images.githubusercontent.com/6772799/45193944-54ebce80-b283-11e8-8dbe-230f27020eb4.png)
