### ISSUE TITLE
在chrome、Edge等浏览器中会跟罗技鼠标驱动自带的平滑滚动冲突

### ISSUE THREAD

**Issue by Wolfsin** [XUJINKAI/OneQuick#46]
具体表现为，滚轮动一下（一格）的情况下，桌面使用正常工作，在chrome或者Edge中使用时，会变成滚动非常多格，以音量来说明，滚动一格会从20直接飙升到70左右；标签栏也类似。在驱动中对chrome单独关闭平滑滚动就正常了，不知道是因为什么。
不知道作者能不能解决这个问题，如果不能解决有没有考虑加入黑名单功能，可以设置哪些应用下不生效？

**Comment by Wolfsin** [comment]
补充一点，看统计数据会发现在chrome中，在规定区域，一次滚动触发了非常多的热键。

**Comment by XUJINKAI** [comment]
感谢反馈，黑名单类似的功能在计划中。
