### ISSUE TITLE
2.0 新版功能计划/投票 ❤👍❗❗❗

### ISSUE THREAD

**Issue by XUJINKAI** [XUJINKAI/OneQuick#48]
自1.2.5版本发布后，OneQuick最基本的功能已经稳定。接下来OneQuick会有一个大的重构及大量新功能更新，但在设计方面面临着一些挑战。
更高的自由度意味着更复杂的界面和逻辑，而想要保持简洁的界面就要对功能有所取舍，如何在二者之间取得平衡是这次更新的重点。

以下列举了2.0版本计划中的**部分**改动，此列表随时会更新，有任何建议请在本贴下留言。
随着开发进度我会逐渐细化本列表并放截图。您也可以关注[OneQuick微博](https://weibo.com/onequick)随时获得信息😃

## 改动及影响

- 移除切换配置文件的功能

仅保留更改配置文件位置的功能，用于多机云盘同步配置。
切换配置的功能通过在文件内分组实现。（就是以前在A和B两个文件之间切换，现在是同一个文件内储存AB两套配置，切换更加灵活）

- 配置文件无法继承

并非绝对不可以，但这会增加作者的工作量。

- 内置功能页

此页中的功能会拆分到其他页中。
OneQuick快捷键拟删除。（显示界面、禁用服务）

### 新特性

可设定热键仅对特定应用生效。

#### 更多可自定义选项

短时间滚轮只触发一次、修改屏幕边缘触发像素宽度、鼠标在屏幕角落“不动”的触发时长等。

#### 更丰富的触发方式

多步快捷键。

#### 更多内置操作

修改HOSTS，启动UWP应用，屏幕亮度等。

**Comment by xqiushi** [comment]
谢谢非常好用，默认快捷键F9和F10调整一下吧。和PS有冲突。

**Comment by hash7in** [comment]
在指定程序中禁用的功能和鼠标Xbutton快捷键定义

**Comment by ghost** [comment]
可以添加一个类似模块化的实现，所有人都可以根据自己的需要编写模块（至少减轻了原作者的负担）

**Comment by do9core** [comment]
我用短语替换当世界语输入法了，所以希望短语替换能有独立快捷键

**Comment by XUJINKAI** [comment]
@do9core 是指给“短语替换”功能一个开关么

**Comment by do9core** [comment]
> @do9core 是指给“短语替换”功能一个开关么

是的，就是这个意思

**Comment by coreur** [comment]
什么时候能出来啊，等不及了

**Comment by XUJINKAI** [comment]
@Reveanime 稍安勿躁，我比你着急😂

**Comment by wyao666** [comment]
啥时候上线啊！   要到期了PRO板

**Comment by XUJINKAI** [comment]
身体原因停了一段时间，抱歉。可能目前的步子有些大了，我需要重新作一下规划。有是肯定有的，但日期没法保证了，实在抱歉。

**Comment by wyao666** [comment]
等了好久了

**Comment by E1nzbern** [comment]
来自2020的催更😁
顺便建议加一个屏幕边缘调屏幕亮度的功能

**Comment by DarthJesusYan** [comment]
能开源吗？

**Comment by XUJINKAI** [comment]
@Herobrine123ABC 2.0准备基础库开源 核心部分不开源

**Comment by yangyyg** [comment]
请求添加一个左右翻页的功能(用于像OneNote、Excel这样的场景下）

**Comment by ADFJASDFJA6** [comment]
希望作者能考虑下加入每个软件自定义鼠标手势的功能，或者全局鼠标手势。目前在用耍下的全局鼠标手势，功能没得说就是对于某些软件还需要调整，我想Quick作为超级效率工具如果能加入可以每个软件可单独定制且没有冲突的手势一定是如虎添翼，本人对于手势软件非常偏爱，这一点在配合一些绘图软件使用非常的便捷，这还仅仅只是复制、删除退出的基本操作。如果能针对软件设置手势对应触发自定义的快捷键的话，效率一定会有更大的提升。Quick牛逼

**Comment by ADFJASDFJA6** [comment]
我才发现我发错了。。。。这是onequick。。。。。说明一下啊，我之前评论的说的是quick啊不一样

**Comment by ABC-upup** [comment]
来自2021的期待

**Comment by yatounoneko** [comment]
如果能将chrome切页的检测机制修正一下就非常好了）

**Comment by CppXL** [comment]
f9和f10能改成双击吗，和windbg冲突了

**Comment by wyao666** [comment]
2023年7月4日 09:22:38

**Comment by changleiy** [comment]
2014年了，还能更新吗？

**Comment by XUJINKAI** [comment]
> 2014年了，还能更新吗？

今年会有

**Comment by XUJINKAI** [comment]
@xqiushi @ZippyZebra75 @imidway @THRILLERLEMON @do9core @coreur @wyao666 @E1nzbern @DarthJesusYan @yangyyg @ADFJASDFJA6 @ABC-upup @yatounoneko @CppXL @changleiy 

#81 新版真的来了。
