### ISSUE TITLE
开机启动导致部分功能失效

### ISSUE THREAD

**Issue by IF-ACT** [XUJINKAI/OneQuick#49]
开机自动运行的onequick部分功能无法正常使用，包括：屏幕边缘操作，窗口不透明度调节等**依赖鼠标滚轮**的快捷功能。
退出onequick重新启动或以管理员身份运行都可以解决。

环境信息：
OneQuickStore x64 1.2.5.36786
Windows 10 Home China x64 1803 (17134.rs4_release)

**Comment by XUJINKAI** [comment]
这个问题我也遇到了，临时解决方法是以管理员权限自启。
先取消或禁用OneQuick自身的自启，然后到计划任务添加命令，参考 #36
