### ISSUE TITLE
Firefox浏览器的标签切换功能BUG

### ISSUE THREAD

**Issue by Ericwong5021** [XUJINKAI/OneQuick#51]
在火狐浏览器使用多标签滚轮切换的时候只能在两个标签页之间切换，并且对滚轮动作的响应很奇怪，功能完全没法正常使用。
相同的配置在Chrom、Edge上标签切换非常流畅，IE则是滚轮向下滚动切换正常，向上滚动的功能不灵敏。

OneQuick很酷很有生产力，希望越做越好φ(>ω<*)

**Comment by XUJINKAI** [comment]
2.0会细化标签页的功能，解决这个问题。

**Comment by ghost** [comment]
![default](https://user-images.githubusercontent.com/18734999/51366304-d0a63380-1b1f-11e9-92c5-e656ef95d217.png)
可能是这个设置引起的，可以试试取消勾选 

> “按下 Ctrl+Tab 时，依照最近使用顺序循环切换标签页”

试一下

**Comment by Ericwong5021** [comment]
> ![default](https://user-images.githubusercontent.com/18734999/51366304-d0a63380-1b1f-11e9-92c5-e656ef95d217.png)
> 可能是这个设置引起的，可以试试取消勾选
> 
> > “按下 Ctrl+Tab 时，依照最近使用顺序循环切换标签页”
> 
> 试一下

是的诶，取消勾选就好了，谢谢!

**Comment by XUJINKAI** [comment]
OneQuick已更新新版，欢迎使用。
