### ISSUE TITLE
滚轮应用切换会导致office无法翻页

### ISSUE THREAD

**Issue by yydlrzc** [XUJINKAI/OneQuick#52]
使用滚轮切换应用,切换到office word后,word无法使用滚轮进行滚动操作

**Comment by ghost** [comment]
这个可能是键盘按键发送顺序的问题（好像是因为Word检测到Alt键没抬起）  试试多按几下 Alt 或者 Ctrl 再翻页？

**Comment by yydlrzc** [comment]
好像确实是这个问题，按一下Alt就可以了

**Comment by XUJINKAI** [comment]
#81 OneQuick已更新新版，欢迎使用。
