### ISSUE TITLE
建议添加一个可激活/隐藏全屏置顶窗体

### ISSUE THREAD

**Issue by nuoicom** [XUJINKAI/OneQuick#53]
就是和本身的 显示/隐藏界面 差不多感觉，但建议可以是【置顶】全面屏范围和在全屏窗口里也可以靠热键启动
添加理由和大致方向：
● 一下窗口全屏后会导致一些滚轮按下失效，只可以使用滑动滚轮（更别说全屏游戏这些独占窗体）
● 很多时候在用一些软件只能靠激活系统win才能启用（就希望能舔加一个双击滚轮【之类】来激活/隐藏一个【置顶】窗体界面供能在很时候能快速使用按下滚轮这些功能）
● 建议窗体是透明（但可自定义图片之类的会更受大众欢迎？）
● 感谢一直的热情开发，我也会推荐给好友使用！

**Comment by XUJINKAI** [comment]
是说一个自定义的操作列表窗口？

**Comment by nuoicom** [comment]
> 是说一个自定义的操作列表窗口？

原谅我我一时间没看懂。。，我的想法简单点说就是类似OneQuick本身的显示/隐藏界面那样启动一个全屏窗口来方便用这些边缘操作

**Comment by XUJINKAI** [comment]
挡住是什么意思？
如果是在某些窗口激活时快捷键失效，可以试试以管理员权限运行程序。

**Comment by ghost** [comment]
> 
> 
> > 快捷键启动一个全屏的界面？
> > 我看不到这样做有什么好处，本来OneQuick的特点就是不遮挡当前桌面+盲操作。
> > 你可以直接说说你想解决哪些问题？
> 
> 就以目前版本来说，一般有些窗口全屏化（不是独占那种）快捷键就会被挡住，这时候就需要启动一下win键（但是中键不能用，会按进那个窗口），我的方法就是启动一个类似mac的Launchpad窗口来按中键。本质上是也许就是想解决一些遮挡问题？😵

这个可能是因为你的那个程序使用管理员权限启动的，所以也需要用 管理员权限启动 OneQuick
