### ISSUE TITLE
开启后鼠标滚轮高延迟，禁用后恢复正常

### ISSUE THREAD

**Issue by kenkangxgwe** [XUJINKAI/OneQuick#54]
在正常窗口中（未触发屏幕边角），滑动滚轮延迟非常严重，同时鼠标移动缓慢，数秒后恢复正常，目前已将 OneQuick 禁用，一切良好。

非个别窗口，基本所有应用窗口都是如此。

**Comment by XUJINKAI** [comment]
如果是启用的时候卡几秒属于正常，如果一直卡确实是问题。
不知是特定应用在前台时这样还是一直这样。
再者，机器配置，操作系统等都会有影响。

**Comment by kenkangxgwe** [comment]
每次滑动滚轮都会如此，按理说，我没有把鼠标移动到边角，滚轮应该不造成额外的影响吧

**Comment by XUJINKAI** [comment]
这个原理是先检测滚轮，再判断位置，所以跟在不在边角无关。
话说只有滚轮时会卡么，鼠标左右键、键盘按键时如何？

**Comment by kenkangxgwe** [comment]
目前只观察到滚轮的问题，我刚刚禁用了开机自启，重启之后手动打开，暂时未发现问题。

**Comment by QIANWC** [comment]
没感觉到遇到题主的高延迟问题，但存在其他问题。
任何界面，滚轮快速滚动时一直发出“嘟嘟嘟”声音，页面滚动速度远低于预期。
感觉滚动指令被缓存了，会慢慢慢慢慢地依次执行缓存指令，所以鼠标还会卡一长段时间。
取消启用或者关闭windows hook可以解决（那还要onequick做啥）。
鼠标：罗技MX Master和MX Master 2S，在公司和家里都有该问题。

**Comment by zrq8** [comment]
和题主问题类似，在《彩虹六号》中（其他应用没事），滚动滚轮，会卡住约两秒，之后恢复正常
取消启用OneQuick可解决

**Comment by zrq8** [comment]
和题主问题类似，在《彩虹六号》中（其他应用没事），滚动滚轮，会卡住约两秒，之后恢复正常
取消启用OneQuick可解决

**Comment by Big-god-Yin** [comment]
> 没感觉到遇到题主的高延迟问题，但存在其他问题。
> 任何界面，滚轮快速滚动时一直发出“嘟嘟嘟”声音，页面滚动速度远低于预期。
> 感觉滚动指令被缓存了，会慢慢慢慢慢地依次执行缓存指令，所以鼠标还会卡一长段时间。
> 取消启用或者关闭windows hook可以解决（那还要onequick做啥）。
> 鼠标：罗技MX Master和MX Master 2S，在公司和家里都有该问题。

你这个问题和题主是一样的，只是描述不同。我也遇到这个问题，严重影响使用。

**Comment by Big-god-Yin** [comment]
希望开发者尽快解决这个问题，现在已经暂停使用onequick

**Comment by zytajoy** [comment]
我已经发现了问题所在，是在“内置功能——应用增强”中，勾选了“在chrome标签上滚轮切换”这个功能造成的，取消勾选之后现象就消失了。
![image](https://user-images.githubusercontent.com/10429274/79090474-6a3caf00-7d7c-11ea-8005-cac5fc1c31f4.png)

**Comment by Big-god-Yin** [comment]
太好了，非常感谢
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zytajoy"<notifications@github.com&gt;; 
发送时间: 2020年4月13日(星期一) 中午11:46
收件人: "OneQuick/Feedback"<Feedback@noreply.github.com&gt;; 
抄送: "∞&amp;#x2122;"<1291948973@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [OneQuick/Feedback] 开启后鼠标滚轮高延迟，禁用后恢复正常 (#54)





 
我已经发现了问题所在，是在“内置功能——应用增强”中，勾选了“在chrome标签上滚轮切换”这个功能造成的，取消勾选之后现象就消失了。

**Comment by QIANWC** [comment]
> 我已经发现了问题所在，是在“内置功能——应用增强”中，勾选了“在chrome标签上滚轮切换”这个功能造成的，取消勾选之后现象就消失了。
> ![image](https://user-images.githubusercontent.com/10429274/79090474-6a3caf00-7d7c-11ea-8005-cac5fc1c31f4.png)

确实解决了，一同干掉了闹心的chrome标签页切换问题，MX Master开了平滑滚动之后只要在标签页上滚动就和抽风一样。

**Comment by mlch911** [comment]
+1

**Comment by yatounoneko** [comment]
这个问题只出现在全屏或无边框的情况下，我玩LOL的时候如果启用了OneQuick也会出现这个情况。不管哪个设备都是一样。
不过我非常喜欢Chrome切换这个功能，最好用最方便没有之一，可惜它却是罪魁祸首
（虽然这个功能在别的国产浏览器中N年前早就出现过了

**Comment by zjw40511** [comment]
我就说为什么我的无极滚轮使用体验跟别人不一样呢，居然是onequick的问题（扶额）

**Comment by XUJINKAI** [comment]
#62
