### ISSUE TITLE
很多时候自定义热键会冲突，所以希望能加个特殊字符+字母的组合热键

### ISSUE THREAD

**Issue by hzchang** [XUJINKAI/OneQuick#56]

**Comment by XUJINKAI** [comment]
@hzchang #81 新版已更新，欢迎使用。新版支持多步热键，一定程度能解决这个问题。至于完全自定义组合键，我再想想怎么搞。

**Comment by XUJINKAI** [comment]
v10新版本已更新，欢迎使用。有关功能需求都整理到一个帖子了，这个就先关了。
