### ISSUE TITLE
启动网易有道词典时报错

### ISSUE THREAD

**Issue by happyTonakai** [XUJINKAI/OneQuick#59]
报错信息见图：[https://img.vim-cn.com/c3/d1444a09adf533239aa7457e02c9cbd527b03e.png](url)

OneQuickStore x64 1.2.5.36786
Windows 10 Pro x64 1903 (18362.19h1_release)
日志中没发现什么奇怪的事情…… 就是Write OneQuick.config
报错时鼠标移动变得卡卡的，点确定还会再次弹出，关闭有道词典之后恢复正常

**Comment by HaoTy** [comment]
我也遇到了，不只是OneQuick，skype的一个组件(SkypeBridge.exe)也报错，似乎是更新1903之后有道的划词会和某些UWP应用产生冲突。估计要么微软解决要么有道解决，和OneQuick关系应该不大。

**Comment by HaoTy** [comment]
可以暂时使用有道7.x版避免这个问题
