### ISSUE TITLE
多显示器下，右侧显示器左上角会被识别成右边缘

### ISSUE THREAD

**Issue by kenkangxgwe** [XUJINKAI/OneQuick#6]
我是双显示器，右侧显示器较小，因此右侧显示器的左上角会被误认为是左侧显示器的右边缘。希望能够改进，感谢！
![image](https://user-images.githubusercontent.com/8650023/31916889-c85735fa-b822-11e7-806b-97058eeb798f.png)

**Comment by XUJINKAI** [comment]
我也俩显示器，并没有这样的问题，你看看是不是鼠标不小心跑左边去了。
不行的话我再查查代码。

**Comment by kenkangxgwe** [comment]
Windows 下不管在那个屏幕上，鼠标靠住边缘四个角都是不会穿到另外其他几个屏幕上的，我试了一下，如果鼠标紧贴1屏的左上角，的确是2屏右边缘的效果，如果鼠标离1屏左上角有大概几个像素的距离的话，就可以正常执行左上角的音量调节功能，但是这样很不方便，一般鼠标都是顶着某一个角进行快捷操作，而不会专门和角落保持一段空隙。我猜想会不会是右边缘的的感知位置和左边缘的感知位置有重叠和优先级判定呢？期待能够解决，谢谢！

**Comment by XUJINKAI** [comment]
已确认问题，是优先级的问题，非常感谢
