### ISSUE TITLE
Windows 更新 1903 后启动失败

### ISSUE THREAD

**Issue by li-fstz** [XUJINKAI/OneQuick#60]
---------------------------
程序崩溃
---------------------------
值不在预期的范围内。

   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)

   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)

   在 MS.Internal.Text.TextInterface.Native.Util.ConvertHresultToException(Int32 hr)

   在 MS.Internal.Text.TextInterface.FontFamily.GetFirstMatchingFont(FontWeight weight, FontStretch stretch, FontStyle style)

   在 MS.Internal.FontFace.PhysicalFontFamily.GetGlyphTypeface(FontStyle style, FontWeight weight, FontStretch stretch)

   在 MS.Internal.FontFace.PhysicalFontFamily.MS.Internal.FontFace.IFontFamily.GetTypefaceMetrics(FontStyle style, FontWeight weight, FontStretch stretch)

   在 System.Windows.Media.Typeface.ConstructCachedTypeface()

   在 System.Windows.Media.Typeface.get_CachedTypeface()

   在 System.Windows.Media.Typeface.CheckFastPathNominalGlyphs(CharacterBufferRange charBufferRange, Double emSize, Single pixelsPerDip, Double scalingFactor, Double widthMax, 

......
---------------------------
确定   
---------------------------

**Comment by XUJINKAI** [comment]
把前边也贴出来啊，日志里有全部的错误信息。

通用的解决办法就是删掉配置文件。
