### ISSUE TITLE
开启Chrome标签滚轮切换后有严重系统冲突

### ISSUE THREAD

**Issue by jeremyjone** [XUJINKAI/OneQuick#61]
问题描述：开启应用增强的`在Chrome标签上滚轮切换`功能后，整个系统都有严重的冲突，不论在什么界面，什么位置，只要滚动鼠标滚轮，整个系统都会变得非常卡，然后音频输出`嘟嘟嘟`的声音，任何地方都非常不顺畅，有时候还会滚动切换虚拟桌面。

系统：win10 64位 1903 企业版
Chrome版本：版本 77.0.3865.90（正式版本） （32 位）
鼠标：雷柏VT350

之前没有此问题，最近出现，不知道是不是和Chrome有关系。没有其他冲突。

**Comment by pengfeidip** [comment]
win10 64位 1903 企业版
我也发现了这个问题，滑动滚轮很卡。不止出现在chrome上，也出现在其它应用里。

**Comment by ForeverBRS** [comment]
win10 21h2 专业版 x64
我在长时间锁屏后唤醒，也出现了这个问题
无论什么鼠标都会

**Comment by XUJINKAI** [comment]
可能与 #62 有关

**Comment by XUJINKAI** [comment]
#81 OneQuick已更新新版，欢迎使用。
