### ISSUE TITLE
鼠标滚轮快速滚动时鼠标指针严重卡顿

### ISSUE THREAD

**Issue by Big-god-Yin** [XUJINKAI/OneQuick#62]
（借用某个问题下的回复）任何界面，滚轮快速滚动时一直发出“嘟嘟嘟”声音，页面滚动速度远低于预期。
感觉滚动指令被缓存了，会慢慢慢慢慢地依次执行缓存指令，所以鼠标还会卡一长段时间。
取消启用或者关闭windows hook可以解决（那还要onequick做啥）

**Comment by zytajoy** [comment]
遇到同样的问题

**Comment by zytajoy** [comment]
我已经发现了问题所在，是在“内置功能——应用增强”中，勾选了“在chrome标签上滚轮切换”这个功能造成的，取消勾选之后现象就消失了。
![image](https://user-images.githubusercontent.com/10429274/79090385-15993400-7d7c-11ea-97f8-ae388c116fc2.png)

**Comment by XUJINKAI** [comment]
@zytajoy @Big-god-Yin #81 OneQuick已更新新版，欢迎使用。
