### ISSUE TITLE
微软Chromium版的Edge浏览器希望也可以得到支持

### ISSUE THREAD

**Issue by Aponio** [XUJINKAI/OneQuick#63]
现在微软的Edge也不是不可以用“滚轮切换标签”，但问题是只可以在   “浏览器全屏时且鼠标置于标签的最上方”，才能切换标签。作者可以试试看。Edge不像谷歌浏览器，只要是放在标签上（任意位置）都可以切换标签。希望作者在下一版可以支持一下Edge浏览器。谢谢。

**Comment by Aponio** [comment]
是我搞错了，虽然是Chromium版本，但是Edge浏览器本身并不支持“在chrome标签上滚轮切换”这个功能，只能用 屏幕边缘 的滚轮进行标签的切换。

**Comment by XUJINKAI** [comment]
#81 OneQuick已更新，欢迎试用新版。
