### ISSUE TITLE
提供一个选项：当使用全屏应用程序时，自动禁用

### ISSUE THREAD

**Issue by keith0305** [XUJINKAI/OneQuick#67]
您好，感谢您提供这个工具，非常好用。
但是有时候当我打游戏时候，会不故意地启动鼠标滚轮作用。

希望您可以提供一个我们英语说的：
"Disable when full screen application is active"

翻译为“全屏应用程序处于活动状态时禁用”。
谢谢。

**Comment by creeeeeek** [comment]
附议

**Comment by XUJINKAI** [comment]
#103
