### ISSUE TITLE
OneKuick开机启动之后所有功能都失效，需要重新启动软件才能解决

### ISSUE THREAD

**Issue by Orustown** [XUJINKAI/OneQuick#68]
Win10 家庭版 64位 Thinkpad
OneQuick 1.2.5

感谢作者开发的软件，很喜欢这个效率软件，用了一个月了，有个问题反馈一下。
设置开机启动之后，有大部分的概率启动后软件功能会失效，
不失效的情况一般都是我在关闭电脑前先关闭了OneQuick。

我自己的解决方法都是，关闭软件重启，可以重新生效，但这样做的话要重新找软件位置。
建议可以在任务栏的右键菜单中加入一个重启软件的选项，这样应该会方便一点，也能解决问题。

**Comment by XUJINKAI** [comment]
OneQuick已更新，此问题先关闭，还有问题的话欢迎反馈。
