### ISSUE TITLE
打FPS类吃鸡游戏（比如APEX）时鼠标滚动滚轮捡装备会非常的卡顿，无法自理的那种卡顿

### ISSUE THREAD

**Issue by selfdialog** [XUJINKAI/OneQuick#69]
一开始我以为系统的问题，我排查了很久是oneQuick的问题，后台关闭OneQuick插件就没问题了，希望作者能排查一下

**Comment by SunnyRx** [comment]
我也受这个问题困扰……
参考https://github.com/OneQuick/Feedback/issues/54#issuecomment-612736806

**Comment by duzp** [comment]
QtCreator 编辑器滚轮也会出现这个问题，而且PC蜂鸣器会嘀嘀嘀响

**Comment by XUJINKAI** [comment]
应该是滚轮触发太频繁，OneQuick处理不过来导致的，后续会专门针对这个问题优化。

**Comment by XUJINKAI** [comment]
#62
