### ISSUE TITLE
内置快捷键在不按下Win键时触发

### ISSUE THREAD

**Issue by kenkangxgwe** [XUJINKAI/OneQuick#7]
在某些情况下，打字按到`w`,`t`或`n`的时候，会触发`Win`+*才会触发的快捷键，（比如输入`n`时会弹出记事本），需要再按一次`Win`键才能恢复正常输入。

**Comment by XUJINKAI** [comment]
和 #2 原因一样，只是表现相反

**Comment by XUJINKAI** [comment]
请更新1.0
