### ISSUE TITLE
左上角不动会受用户账户控制影响

### ISSUE THREAD

**Issue by 1747729173** [XUJINKAI/OneQuick#70]
OneQuickStore x64 1.2.5.36786
Windows 10 Home China x64 1909 (18363.19h1_release)
打开某些软件会提示用户账户控制（你要允许该应用对你的设备进行更改吗），会触发左上角不动的命令。（其他角落的不会触发，屏幕上鼠标还是原位置，应该是打开的时候鼠标处于默认位置左上角）

**Comment by XUJINKAI** [comment]
后续优化
