### ISSUE TITLE
onequick配置文件读取错误，要求配置preference.cfg

### ISSUE THREAD

**Issue by zanyangtao** [XUJINKAI/OneQuick#72]
每次打开都打不开。显示标题的提示，打开一个文件夹。D:\Users\zanyangtao\Documents\OneQuick
但是cfg文件不能直接更改。
[OneQuick.log](https://github.com/OneQuick/Feedback/files/7098999/OneQuick.log)

**Comment by XUJINKAI** [comment]
https://github.com/OneQuick/Feedback/issues/78
