### ISSUE TITLE
Mac/Linux是否能被支持？

### ISSUE THREAD

**Issue by product-think2049** [XUJINKAI/OneQuick#75]
很喜欢软件中的“滚轮翻页”功能（日常看非常多的网页），用它能快速的下滑网页（Page Down）
在Mac与Linux平台上，还没找到类似的软件

**Comment by product-think2049** [comment]
感谢开发者！

**Comment by XUJINKAI** [comment]
目前没有这个打算，这个软件的技术栈是C#/WPF，而且API严重依赖win32，支持其他平台几乎等于重写。
