### ISSUE TITLE
希望增加按键映射到鼠标的功能

### ISSUE THREAD

**Issue by wufeng1740** [XUJINKAI/OneQuick#79]
希望能有映射到鼠标按键的功能，这样就可以将键盘的按键或者组合键模拟成鼠标按键（左，右，或中键），不知道是按键映射好还是自定义热键实现起来好一些。
最终想要的效果是可以用键盘实现鼠标的点按，双击，长按的操作。
不知道实现起来是否方便，对我很有用~目前市面上很难找到键盘实现鼠标按键的方法，所以觉得这个软件可能刚好符合这个使用场景。
谢谢。

**Comment by XUJINKAI** [comment]
在最新的10.3版本中，已支持对鼠标按键的模拟。

**Comment by wufeng1740** [comment]
太好啦～没想到这个想法能被实现～继续支持～

**Comment by XUJINKAI** [comment]
@wufeng1740 感谢支持，可以的话也请到应用商店给个好评❤️

**Comment by wufeng1740** [comment]
一定一定～
刚刚更新软件试了一下，发现新的v10页面很好看，也有了新的功能特别棒～
然后我尝试了映射鼠标按键的功能。我用键盘映射鼠标左键，发现只能实现点按，不能模拟鼠标长按的状态。这样就无法替代鼠标来长按拖拽窗口了，不知道是我没有设置好，还是目前的这个功能还没法有很完善呢。

**Comment by XUJINKAI** [comment]
@wufeng1740  拖拽这个倒是没考虑到，下个版本优化吧

**Comment by wufeng1740** [comment]
@XUJINKAI 你回复的好快，期待～
