### ISSUE TITLE
OneQuick 10.0 已更新！

### ISSUE THREAD

**Issue by XUJINKAI** [XUJINKAI/OneQuick#81]
是很久了😂 总之更新了。
现在可以去应用商店下载。

这次是完全从头写的全新版本，目前功能和原版差不多（但已经有多步热键了），**后续会来几波更大的**。

使用之类的问题可以提在这个帖子下。

**Comment by XUJINKAI** [comment]
先说一个大家应该会关心的问题：性能如何？

新版本的技术架构是：C#后端+WPF套WebView+Vue3开发。

平时不开主窗口时，C#后端内存占用30MB，同时因为我重构精简了代码+C#升级加成，效率比旧版有提升。

打开主窗口时，webview会额外占用90MB内存，不过关闭后会执行一次GC，内存占用会掉回去。

**Comment by KUGDracula** [comment]
新版本更新后没法打开运行哦，win10

**Comment by KUGDracula** [comment]
能不能提供一个历史版本的下载链接呢

**Comment by XUJINKAI** [comment]
@KUGDracula 目前只有应用商店的版本，没法提供历史版本。麻烦描述一下win10是什么版本，没法运行的症状是什么。

**Comment by Followtoshe** [comment]
大佬你好，我10.0.1.0版本夜间模式字体显示是有问题的。PS：另说一句，这六年我实在等得太久了，一直以为您放弃这个软件的开发了！可喜可贺！！！
![image](https://github.com/user-attachments/assets/49fcb0ef-7b77-475c-a2f1-99fd2e7505bb)

**Comment by Followtoshe** [comment]
sry，更新了10.0.3.0版本就没这个问题了~

**Comment by KUGDracula** [comment]
> @KUGDracula 目前只有应用商店的版本，没法提供历史版本。麻烦描述一下win10是什么版本，没法运行的症状是什么。

版本	Windows 10 专业版
版本号	22H2
安装日期	‎2023/‎2/‎3
操作系统内部版本	19045.4780
体验	Windows Feature Experience Pack 1000.19060.1000.0

问题：在微软商店onequick界面点击“打开”
![image](https://github.com/user-attachments/assets/b49cafa3-8412-4a63-8319-ebf113038e90)
或者在win开始界面右键管理员运行
![image](https://github.com/user-attachments/assets/8c92e59d-30e0-4d03-a041-bbe46447b1a3)

之后都无法唤醒onequick的交互界面，并且查看任务管理器，也没有onequick相关的进程；

在多次卸载重装、且重启电脑的情况下，都无法打开该程序

**Comment by KUGDracula** [comment]
安装后，exe文件大小都为0字节
![image](https://github.com/user-attachments/assets/678bd776-e653-4e43-9ce8-eda4edbb1539)
![image](https://github.com/user-attachments/assets/1c0225ea-82a6-433f-a13c-f8c4875c173b)

**Comment by XUJINKAI** [comment]
@KUGDracula 0字节那是个占位符，你看其他应用都是0字节。

真正的安装路径在 C:\Program Files\WindowsApps\55774JinkaiXu.252258CF1F9E6_10.0.3.0_x64__p5dcp4q3yn5jt\OneQuick
这个路径只能直接粘贴打开，不能逐级点进去，因为WindowsApps这个目录有权限限制。

你可以打开日志看看：
先到这个目录：<用户名>\AppData\Local\Packages\55774JinkaiXu.252258CF1F9E6_p5dcp4q3yn5jt\LocalCache\Local\OneQuick
先修改setting.json，添加 **"log.level": "Debug"**
![image](https://github.com/user-attachments/assets/cf968b57-a042-40ff-842e-a2615a8cb65e)
然后看看log目录里的输出

**Comment by KUGDracula** [comment]
> @KUGDracula 0字节那是个占位符，你看其他应用都是0字节。
> 
> 真正的安装路径在 C:\Program Files\WindowsApps\55774JinkaiXu.252258CF1F9E6_10.0.3.0_x64__p5dcp4q3yn5jt\OneQuick 这个路径只能直接粘贴打开，不能逐级点进去，因为WindowsApps这个目录有权限限制。
> 
> 你可以打开日志看看： 先到这个目录：<用户名>\AppData\Local\Packages\55774JinkaiXu.252258CF1F9E6_p5dcp4q3yn5jt\LocalCache\Local\OneQuick 先修改setting.json，添加 **"log.level": "Debug"** ![image](https://private-user-images.githubusercontent.com/6772799/361295651-cf968b57-a042-40ff-842e-a2615a8cb65e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzA3MTksIm5iZiI6MTcyNDY3MDQxOSwicGF0aCI6Ii82NzcyNzk5LzM2MTI5NTY1MS1jZjk2OGI1Ny1hMDQyLTQwZmYtODQyZS1hMjYxNWE4Y2I2NWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjZUMTEwNjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWE0NDllNTI1MTRkMzlhMTdhZTNiZGQ1MDZmYjc0NGU5YzUwMzk1YzMzYzQzZGVkZjZjOWRjZGFhNmJlZTZiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RvdXxED4YaDisdAdEEDXYSUqLmA8i63MCCJ0V6jtj0s) 然后看看log目录里的输出

![image](https://github.com/user-attachments/assets/2f91f357-1303-4f75-83e4-bc5210d80eb9)
![image](https://github.com/user-attachments/assets/1c7e395e-4c61-4e3d-867a-19f247b4d016)

我这个文件路径里没有OneQuick，只有Microsoft，且该文件夹内是空的

**Comment by XUJINKAI** [comment]
@KUGDracula 我新开了一个帖子 #87 
你可以重点看看事件查看器里有没有东西，不行的话重置应用商店和重装onequick看看。
我有一台机子也是相同的系统，但没有问题。
