### ISSUE TITLE
屏幕边缘「运行命令」配置问题

### ISSUE THREAD

**Issue by SunnyRx** [XUJINKAI/OneQuick#83]
# 现象

在配置屏幕边缘的操作时，修改不同操作的「运行命令」后，所有的「运行命令」会同时被更改。

# 期望

希望能够为不同操作的「运行命令」配置独立的命令。

**Comment by XUJINKAI** [comment]
这确实是个bug，感谢。

**Comment by XUJINKAI** [comment]
v10.0.2 已修复，新版一般1天左右可用，最长3天。
