### ISSUE TITLE
深色模式适配问题

### ISSUE THREAD

**Issue by SunnyRx** [XUJINKAI/OneQuick#84]
当前 OneQuick 打开后默认界面是深色模式，但没有找到相关的设置选项，可能是随系统设置的。

然后似乎界面没有很好地适配深色模式，导致很多文字不清晰。

![image](https://github.com/user-attachments/assets/fa9a1b7f-f7ba-4bd0-b6b5-e9304d6b3ef1)
![image](https://github.com/user-attachments/assets/2f7c25f0-ab4d-43dc-b917-d82c92de3b6e)

**Comment by XUJINKAI** [comment]
v10.0.3 已修复，需要1到3天上应用商店。

**Comment by SunnyRx** [comment]
这个问题在v10.4.2又发生了

<img width="1184" height="661" alt="Image" src="https://github.com/user-attachments/assets/4d0d1622-d5e5-491e-88f4-80e2831b1d4c" />

<img width="1184" height="661" alt="Image" src="https://github.com/user-attachments/assets/7e887c86-1a2d-4fa8-9e67-3db284ecf795" />
