### ISSUE TITLE
屏幕边缘「运行命令」显示问题

### ISSUE THREAD

**Issue by SunnyRx** [XUJINKAI/OneQuick#85]
关联问题 #83 

版本：v10.0.3.0

# 现象

在不同的操作中，如果配置了不同的「运行命令」，会出现显示不正确的情况。

举例：若在上边缘设置了「运行命令」A，然后在下边缘设置了「运行命令」B，此时切换到上边缘时，界面上会错误地显示「运行命令」B。然而，实际上，上边缘的操作仍然是「运行命令」A。  

似乎是切换到其它「运行命令」时，没有刷新里面的值。

**Comment by XUJINKAI** [comment]
🤦‍♂️确实，需要先点击其他没有运行命令的格子再点回来才会正确显示

**Comment by XUJINKAI** [comment]
10.0.4版本已修复，应用商店需要1到3天上架。
