### ISSUE TITLE
短语替换的缺陷

### ISSUE THREAD

**Issue by damao33** [XUJINKAI/OneQuick#86]
设置如图
![image](https://github.com/user-attachments/assets/0618f191-d6f3-46d0-a09a-2f459e099df2)
实际替换出来的短语如下：
![image](https://github.com/user-attachments/assets/9e736331-e6d8-4dcd-84f9-afff93f2d98d)

旧版本功能正常，升级新版后出现的异常

**Comment by XUJINKAI** [comment]
这个好像和IDE还有关系，我自己测试系统自己的notepad就不好使，旧版本也不行。不知你用的什么IDE，能不能多测试一些场景？谢谢了

**Comment by XUJINKAI** [comment]
也可能和系统反应速度有关系，因为我自己电脑没问题。之后我试着在删除和输出之间加一些延迟看看能不能改善。

**Comment by damao33** [comment]
> 也可能和系统反应速度有关系，因为我自己电脑没问题。之后我试着在删除和输出之间加一些延迟看看能不能改善。

这个可能性倒还比较小，我工作电脑的配置还可以。至于ide的问题，我用的是pycharm2023的某个版本，明天上班我多换几个场景试一下～

**Comment by XUJINKAI** [comment]
我更新了一个10.0.4版本，应用商店可能需要1到3天上架。

麻烦你确认更新到新版后，
去应用的配置文件夹 C:\Users\<用户名>\AppData\Local\Packages\55774JinkaiXu.252258CF1F9E6_p5dcp4q3yn5jt\LocalCache\Local\OneQuick，修改setting.json，添加一行"debug.sendTextMethod": 2，这个数字可以是1234中的一个。
**注意：修改的时候需要先退出OneQuick，改完以后再启动。**

看看哪些方法可以正常运作。数字越小效率越高，不过一般也感觉不出来。

**Comment by damao33** [comment]
> 我更新了一个10.0.4版本，应用商店可能需要1到3天上架。
> 
> 麻烦你确认更新到新版后， 去应用的配置文件夹 C:\Users<用户名>\AppData\Local\Packages\55774JinkaiXu.252258CF1F9E6_p5dcp4q3yn5jt\LocalCache\Local\OneQuick，修改setting.json，添加一行"debug.sendTextMethod": 2，这个数字可以是1234中的一个。 **注意：修改的时候需要先退出OneQuick，改完以后再启动。**
> 
> 看看哪些方法可以正常运作。数字越小效率越高，不过一般也感觉不出来。

今天测了以下，所有输入框都有相同的问题，跟IDE没关系；把参数改成2功能运行正常，但是输出替换词的时候感觉有明显卡顿，改成1/3/4都不行，都会有一个.且位置不同

**Comment by XUJINKAI** [comment]
其实旧版本也有这个卡顿，是删除键和文字之间的延迟。

问题先开着吧，我之后调整一下这个功能。

**Comment by XUJINKAI** [comment]
新的10.1版本可以在设置面板里调整这些选项，打开Flags，Send Text Back Delay就是中间那一下卡顿的延时，目前调整到了10ms。
