### ISSUE TITLE
配置文件读取&复制执行bug

### ISSUE THREAD

**Issue by AI4CT** [XUJINKAI/OneQuick#88]
1. 10.0版本后能否读取旧版本保存的配置文件？即使已经升级专业版，也没有相应的功能。
2. 10.0.4.0版本使用复制执行时，CSDN导向错误，执行电脑的上一步操作或者复制当前标签页，同样的代码在另一台电脑（10.0.3.0）上可以正常使用。提供执行代码，请作者进行测试：https://so.csdn.net/so/search?spm=1010.2135.3001.4498&q=%s

**Comment by AI4CT** [comment]
![Snipaste_2024-08-31_13-08-44](https://github.com/user-attachments/assets/806d2f66-e861-43e0-913e-6d380486cd73)

**Comment by XUJINKAI** [comment]
1. 旧版配置默认是会升级的，旧版配置在“我的文档”文件夹中，升级后这个文件夹会移走。

目前升级旧配置的逻辑比较复杂，只有程序启动时，检测到旧版配置并且没有新配置，才会尝试去读。

如果确实失败了，可以等下个版本，我加个手动读取的操作。

2. 这个问题我没有遇到，而且10.0.3和10.0.4版本只改了两个小bug。你试一下把CSDN这个【C】改成其他按键，可能是别的配置导致的。

**Comment by AI4CT** [comment]
1、我在一台新电脑上安装了10.0的版本，想把旧电脑的配置移植过来，发现没有相应的读取功能，加一个手动读取就好了；
2、【C】换成其他键也是不行，但我用百度学术、百度翻译、知乎、B站、百度、Google都可以实现这个功能。

**Comment by XUJINKAI** [comment]
现在更新了10.1版本，设置 - 配置管理 - 高级 里，有导入旧版配置的选项。
至于第二个问题，我目前没有碰到，按道理所有网址应该是一样的。你可以试试去 设置 - Flags里，调整Run URL Method的值有没有改善，如果还有问题的话建议新开一个issue

**Comment by AI4CT** [comment]
将Run Url Method设置为2就好了！非常感谢作者！
另外还解决了复制执行时闪黑框的问题，意外之喜！
另外一点，还支持读取旧版本config格式的配置文件，良心大大滴好！！！
![image](https://github.com/user-attachments/assets/38520620-8263-40c4-958a-281b3fc8b61c)

**Comment by XUJINKAI** [comment]
感谢支持，可以的话麻烦到应用商店给个好评❤️
