### ISSUE TITLE
复制执行问题

### ISSUE THREAD

**Issue by tonkryon** [XUJINKAI/OneQuick#89]
win11 23H2 系统  使用10.0.4版本  每次使用复制执行功能 会出现窗口闪烁（类似命令提示符的窗口大概0.1S消失）非常影响体验，
几年前的老版本没有这个问题

**Comment by XUJINKAI** [comment]
现在可以更新10.1版本，进设置/Flags里，调整**Run URL Method**的值，试试哪个方法不会有闪烁

![image](https://github.com/user-attachments/assets/6d17c63f-b314-4daf-b1d5-e6aa3f0141d0)
