### ISSUE TITLE
会有买断版吗？

### ISSUE THREAD

**Issue by bitons** [XUJINKAI/OneQuick#90]

**Comment by XUJINKAI** [comment]
将来如果准备好了，会有的。

正好调查一下，大家能接受什么样的付费方式，以及心理价位是多少。

1是订阅，就是现在的方式，订阅期间享受全部功能。

2.1是小版本买断，大版本重新付费。但这样商店里会出现一堆不同的版本，感觉不利于推广，维护也麻烦。
2.2算一种变种，就是按功能付费。这种...感觉跟氪金游戏是的🤣

3就是完全买断，但这样价格会比较高。

**Comment by bitons** [comment]
1，3

**Comment by Followtoshe** [comment]
订阅和买断都能接受，不过对于开发者来说感觉订阅制会好一些，毕竟维护也需要成本。

**Comment by asanokiyoe** [comment]
2.2也不错，我就是某几个功能重度使用但有些用不上

**Comment by XUJINKAI** [comment]
买断版来了，更新10.3然后去许可证页面就有。

最终还是选择了大版本更新的模式，不过v10计划中的功能还有不少呢。

至于维护成本，只能说本来也不赚钱🤣无所谓了
