### ISSUE TITLE
屏幕边缘的滚轮静止功能 & 多屏幕配置

### ISSUE THREAD

**Issue by AI4CT** [XUJINKAI/OneQuick#92]
1、之前版本有鼠标移动到屏幕边缘后出发命令的功能，我设置为左下角关闭显示器，这在公共场合比较常用，现版本取消了。请问之后还会更新吗？
2、看到10.1版本更新了屏幕配置的功能，有三个问题：（1）点击<系统显示设置>时会闪出黑框，然后再显示设置窗口；（2）设置中的多屏幕排列方式与界面中显示的排列方式不匹配；（3）能否增加多屏幕场景下不同屏幕的边缘触发命令定制化功能？
![image](https://github.com/user-attachments/assets/a983446b-076f-40a9-beca-46fbd552f550)
![image](https://github.com/user-attachments/assets/c7ceabb3-9aae-4e6e-bf2a-7ad3cce55fc3)

**Comment by XUJINKAI** [comment]
#91 第一个问题跟这个重复了，旧版本这个功能其实没做好，之后会回归的。
屏幕配置还在优化中，右边那个显示问题应该是没考虑旋转，功能应该是正常的。
第三个问题，细分不同屏幕的屏幕边缘，我不确定要不要有，感觉这样会过于复杂。
