### ISSUE TITLE
管理员权限的问题

### ISSUE THREAD

**Issue by BUERSAN** [XUJINKAI/OneQuick#94]
新版本复制执行会有问题，执行会跳控制台窗口影响体验，并且执行触发后会有不能准确打开目标网站的问题，会变成打开浏览历史里的网站，规律目前还没发现，好像和配置里的地址有关系？哔哩哔哩和谷歌没问题，知乎淘宝京东就不行

边角执行也有时好时坏的问题，有时候全屏应用可用，有时候桌面都不能用，得重开软件

并且我这里微软购买专业版会有问题，点开闪退

最好是用微软外的购买方式比较好一点，联网账号绑定购买，当然买断制感觉会好很多，价格100rmb以下都能接受吧，不过还是得把基础内容做好啊，新版感觉不如老版，问题还是太多

最好能够提供老版本

**Comment by XUJINKAI** [comment]
#89 跳控制台的问题可以先参考这个帖子解决

麻烦问一下你的电脑是什么操作系统？这些问题好像不同的环境不一样。点击软件开始面板下边的环境信息就可以看到。

感谢你的建议。

**Comment by XUJINKAI** [comment]
边角失效的问题，可能和当前的应用有关，不知你有没有注意过失效时当前激活的是什么软件，是不是管理员权限的软件，不知这方面有没有规律？

**Comment by BUERSAN** [comment]
更新了版本后 Run Url Method 改成2后控制台和错误网站的问题解决了

升级专业版还是闪退，还是希望能够改下付费模式，别死抱着微软商店哩，如果是买断制必入


App: OneQuick Store x64 Release 10.1.2 (783b4d3)
Env: Run as Administrator, args: ""
OS:  Microsoft Windows 11 专业版 x64 23H2 (Build 22631.2715)
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz 2208 MHz

**Comment by XUJINKAI** [comment]
看来是因为以管理员权限启动导致的，目前对于管理员权限的处理还没写好，以后更新会改善。

微软商店这个....🤣微软确实让人头疼，感谢你的建议。

**Comment by XUJINKAI** [comment]
经过测试，管理员权限运行的程序，没法用微软的购买页面，这是Windows自己的限制。

目前只能先回到普通权限再购买，我之后会解决这个问题。

**Comment by Tanler** [comment]
> 看来是因为以管理员权限启动导致的，目前对于管理员权限的处理还没写好，以后更新会改善。
> 
> 微软商店这个....🤣微软确实让人头疼，感谢你的建议。

建议增加一个默认以管理员权限启动的选项

**Comment by XUJINKAI** [comment]
是有这个打算的，这个功能在开发中。

**Comment by XUJINKAI** [comment]
新版10.3已经加入了管理员权限启动的选项。
